### ISSUE TITLE
JSONObject["sitemap"] not a string

### ISSUE THREAD

**Issue by DanStasiak** [openhab/openhab-cloud#18] opened 2016-12-21 07:05 UTC
I have the an error please help.

2016-12-20 21:02:54.444 [ERROR] [o.o.i.o.internal.CloudClient ] - JSONObject["sitemap"] not a string.

Anyone have a idea what could be wrong. It seems to happen at an update of item states to the myopenHAB Cloud.

I'm using/testing the version org.openhab.io.openhabcloud_1.9.0.201612192331.jar

**Comment by marziman** [comment] 2016-12-22 09:41
@DanStasiak,
hi what are you using? OH2 or OH1.
Can you explain a little your setup, that we are able to reproduce?

Thanks!

**Comment by marziman** [comment] 2017-01-02 22:46
@DanStasiak,
this is not an openHAB cloud issue.
See here https://github.com/openhab/openhab/issues/3772

I will close it here, since it should be tracked at the right spot.

**Closed by marziman** 2017-01-02 22:46 UTC
