### ISSUE TITLE
new openhab install--unable to make changes via https://home.myopenhab.org

### ISSUE THREAD

**Issue by btrebor** [openhab/openhab-cloud#128] opened 2017-09-28 19:02 UTC
I just installed openhab2 on Raspberry Pi 3. When connected to lan I can connect to my R-Pi via IP address and makes changes (i.e., adding bindings, editing configurations, etc.). when off my lan and using internet elsewhere, I am unable to make changes to my openhab. I can log into my openhab via myopenhab, it shows I am online, I can see my existing bindings, items, etc, but I am not able to add binding, edit configurations, etc. I get "Error: 504 - Gateway Timeout".

**Comment by btrebor** [comment] 2017-09-29 03:57
I re-installed openhab2 on the Raspberry Pi 3 to make sure it wasn't a faulty install. Same issue.

**Comment by sihui62** [comment] 2017-09-29 08:24
I can confirm this issue, build #1050.

Related community forum thread:

https://community.openhab.org/t/new-raspberry-pi-install-myopenhab-error-504/34581

**Comment by tsheldon** [comment] 2017-09-29 16:05
Looks like this is a duplicate of https://github.com/openhab/openhab-cloud/issues/31

**Comment by marziman** [comment] 2017-09-29 16:12
Hello,
I will investigate this the upcomming days.
It is a duplicate and I hope we can fix this soon.
I will close this for now and track it at the other issue.
BR Mehmet

**Closed by marziman** 2017-09-29 16:12 UTC
