### ISSUE TITLE
Special characters in password cause login problems

### ISSUE THREAD

**Issue by glesik** [openhab/openhab-cloud#108] opened 2017-06-03 19:02 UTC
I have a password which contains characters (slashes, brackets, angle brackets, tildes and semicolons). Everything works fine when I login via https://myopenhab.org/, but when I use Android app or log out and go directly to the sitemap (e.g. https://home.myopenhab.org/basicui/app), the password is not accepted.

I created another user and set its password to only letters and numbers and it works fine.

By the way, changing the password in question didn't work yesterday, but this may be related to #92.

**Comment by FlorianSW** [comment] 2017-06-11 14:48
Hmm, I can't reproduce this behaviour locally :/ It's possible that it is already fixed in the master version of openhab-cloud. I assume you simply get the login dialog again without any error message, right?

The second problem you describe is fixed by #92.

**Comment by glesik** [comment] 2017-06-12 07:09
Yes, the modal login window would just pop up again when using the problematic password.

Unfortunately I forgot to mention the colon symbol (":") in the password. I've just tried using password recovery and it looks like it's exactly the colon causing the trouble. Can this have something to do with "user:password" format in HTTP Basic Auth?

**Comment by FlorianSW** [comment] 2017-06-12 08:14
It shoudl work, as Basic auth allows colons in the password (at least from the RfC), however, there's an issue for the authentication module we use: https://github.com/jaredhanson/passport-http/issues/20 and a fix, which isn't merged, unfortunately. I'll ask there, if this issue will be fixed. If there's no response, I'll check, how we can work around this in our code :) Thanks for spotting!

**Comment by marziman** [comment] 2018-01-20 23:30
This is fixed with https://github.com/openhab/openhab-cloud/pull/110
I am closing this one, since I could create a pw with all those mentioned characters.

**Closed by marziman** 2018-01-20 23:30 UTC
